{% set name = "jupyter-drives" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_drives-{{ version }}.tar.gz
  sha256: 15aaac696a734176a6fce8dfc965f9c9eb9f06479f0f396695090d9452c5c4e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder >=0.3.2
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python {{ python_min }}
    - obstore >=0.3.0b,<0.4
    - arro3-core >=0.2.1,<0.3
    - pyarrow >=18.0.0,<19.0.0
    - aiobotocore >=2.15.2,<2.16.0
    - boto3 >=1.35.36,<1.36.0
    - fsspec >=2024.10.0,<2024.11.0
    - s3fs >=2024.10.0,<2024.11.0
    - jupyter_server >=2.14.2,<3
    - apache-libcloud >=3.8.0,<4
    - entrypoints >=0.4,<0.5
    - httpx >=0.25.1,<0.26

test:
  imports:
    - jupyter_drives
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QuantStack/jupyter-drives
  summary: A Jupyter extension to support drives in the backend.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DenisaCG
    - jtpio
